name: Docker-Publish

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker build WebApi
        run: docker build -t ricardozambon/smart-school-webapi .
        working-directory: ./SmartSchool.WebApi
        
      - name: Docker build Angular
        run: docker build -t ricardozambon/smart-school-angular .
        working-directory: ./SmartSchool.Angular

      - name: Push WebApi to DockerHub
        run: |
          docker tag ricardozambon/smart-school-webapi:latest ricardozambon/smart-school-webapi:${GITHUB_REF:11}
          docker push ricardozambon/smart-school-webapi:${GITHUB_REF:11}
          docker push ricardozambon/smart-school-webapi:latest

      - name: Push Angular to DockerHub
        run: |
          docker tag ricardozambon/smart-school-angular:latest ricardozambon/smart-school-angular:${GITHUB_REF:11}
          docker push ricardozambon/smart-school-angular:${GITHUB_REF:11}
          docker push ricardozambon/smart-school-angular:latest
